# Perfect 2 node network, no noise from either computation on the nodes or communication between nodes
qdevice_cfg: &qdevice_cfg
  num_qubits: 10

  # noise model
  single_qubit_gate_depolar_prob: 0.0
  two_qubit_gate_depolar_prob: 0.0
  # initialization error of the electron spin
  electron_init_depolar_prob: 0.0
  # error of the single-qubit gate
  electron_single_qubit_depolar_prob: 0.0
  # Chance of 0 being measured as 1
  prob_error_0: 0.0
  # Chance of 1 being measured as 0
  prob_error_1: 0.0
  # initialization error of the carbon nuclear spin
  carbon_init_depolar_prob: 0.0
  # error of the Z-rotation gate on the carbon nuclear spin
  carbon_z_rot_depolar_prob: 0.0
  # error of the native NV two-qubit gate
  ec_gate_depolar_prob: 0.0

stacks:
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

links:
  - stack1: Alice
    stack2: Bob
    typ: perfect
    cfg:
      dummy: null